sudo: false
language: node_js
cache:
    directories:
        - node_modules
notifications:
    email: false
before_install:
    # Travis CI only does a shallow clone of the repository. We need to get the 'master' branch
    - "git remote set-branches origin master && git fetch && git checkout master && git checkout -"
node_js:
    - "7"
script:
    - npm start
